CC-14: Implemented selector checkbox control
Components-care/react-components pull request #12
Opened 2020-12-18 14:32 UTC by vishesh-ats

https://github.com/Components-care/backlog/issues/14

2020-12-18 15:06 UTC, TQjona requested changes

2020-12-18 15:06 UTC, TQjona commented on src/standalone/Selector/MultiSelectWithCheckBox.tsx
> +interface MultiSelectWithCheckBoxProps extends SelectProps {
export all type definitions (interfaces and types)

2020-12-18 15:06 UTC, TQjona commented on src/stories/standalone/Selector/MultiWithCheckBox.story.tsx
> +interface MultiSelectOption {
instead of copy-pasting this from the component class to here, export it and import it here

2020-12-21 06:28 UTC, vishesh-ats commented on src/standalone/Selector/MultiSelectWithCheckBox.tsx
> +	options: MultiSelectOption[];
@TQjona , Updated changes. Please Review.

2020-12-21 06:28 UTC, vishesh-ats commented
@TQjona , Updated all suggested changes. Please Review.

2020-12-21 07:36 UTC, TQjona approved these changes

2020-12-21 07:36 UTC, merged