CC-13: Replaced pen icon and changes for save signature
Components-care/react-components pull request #19
Opened 2021-01-05 15:14 UTC by vishesh-ats

https://github.com/Components-care/backlog/issues/13

2021-01-05 16:16 UTC, TQjona approved these changes

2021-01-05 16:17 UTC, TQjona requested changes
Move the Icon to the Icons group

2021-01-06 06:19 UTC, vishesh-ats commented
@TQjona ,
> Move the Icon to the Icons group
- Done. Please Review

2021-01-06 08:06 UTC, TQjona approved these changes

2021-01-06 08:06 UTC, merged