CC-65 UIKit Date Inputs: Support entering dates via keyboard
Components-care/react-components pull request #43
Opened 2021-02-25 05:53 UTC by Dharmik-atharva

(https://github.com/Components-care/backlog/issues/65)

- Add TextField with endAdornment for openInfo and open calender
- Support keyboard input 
- Show error for invalid date

2021-02-25 07:47 UTC, TQjona commented
Control doesn't call onError event callback -> Needed for Form Engine to block form submit

2021-02-25 11:05 UTC, Dharmik-atharva commented
@TQjona, Requested changes done, Please review

2021-02-26 11:11 UTC, TQjona requested changes

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +	value: Date | null;
missing documentation on all these fields

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +		if (onError && isError) {
this should also fire when there is no longer an error with `onError(null)`

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +					ccI18n.t(
this should be overridable (there should be something in the picker props for this label)
`props.invalidDateMessage ?? ccI18n.t(...)`

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +			} else {
else and if can be combined

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +				onOpen={() => setIsOpen(true)}
missing useCallback for onOpen and onClose.

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +				TextFieldComponent={() => null}
TextFieldComponent can be made a static variable outside of the component to avoid rerendering
`const renderTextFieldComponent = () => null;`

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +								<IconButton onClick={() => setIsOpen(true)}>
missing useCallback

2021-02-26 11:11 UTC, TQjona commented on src/standalone/UIKit/InputControls/DateInput.tsx
> +				InputProps={{
InputProps should be stored in useMemo. No need to rerender the end adornments every time this component rerenders.

2021-02-26 11:11 UTC, TQjona commented on src/stories/standalone/UIKit/InputControls/DateInput.story.tsx
> +			onError={handleError}
The useCallback here is unnecessary, you can just pass onError directly or even write `action("onError")` in-line

2021-02-26 17:36 UTC, TQjona approved these changes

2021-02-26 17:36 UTC, merged